# -*- coding: utf-8 -*-
"""Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9ByxARHw2XC5qfBHmJiBbT8l6x1EwQ6
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

data = pd.read_csv('/content/data2.csv')
print(data)

print(data['Fraud'].value_counts())

# Convert categorical 'Profession' column to numerical using one-hot encoding
data = pd.get_dummies(data, columns=['Profession'], drop_first=True)

# Drop the 'Expiry' column as it contains string values that cannot be directly used by the model
X = data.drop(['Fraud', 'Expiry'], axis=1)
y = data['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("confusion_matrix:",confusion_matrix(y_test, y_pred))
print("classification_report:",classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))