# -*- coding: utf-8 -*-
"""Resume Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ow8ckSxzmnrf6GJEiJeJUlIwl1UkHjeZ
"""

import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nltk.download('stopwords')

df = pd.read_csv("/content/clean_resume_screening_dataset.csv")

print(df.head())


stop_words = set(stopwords.words('english'))

def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z ]', '', text)

    # Tokenization
    words = text.split()

    # Remove stopwords
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df['Cleaned_Resume'] = df['Resume_Text'].apply(clean_text)

print(df[['Resume_Text', 'Cleaned_Resume']].head())

X = df['Cleaned_Resume']
y = df['Category']

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_tfidf,y,test_size=0.2, random_state=42)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy :", accuracy)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

new_resume = """
Python SQL Power BI Excel Tableau
Worked on dashboards and data analysis projects
"""

# Clean resume
cleaned_resume = clean_text(new_resume)

# Convert into TF-IDF
resume_vector = tfidf.transform([cleaned_resume])

# Predict category
prediction = model.predict(resume_vector)

print("\nPredicted Job Category :", prediction[0])

import pickle

pickle.dump(model, open("resume_model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

print("\nModel Saved Successfully")