# -*- coding: utf-8 -*-
"""Sentiment Analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c29m8LtTdGQdyVY_r7uZcZHYbvsVNa2m
"""

import pandas as pd
import nltk
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

print("Loading data set")
df = pd.read_csv('/content/imdb_balanced_dataset.csv')
print(df.head())

df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})

print(df.head())

def preprocess_text(text):
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in string.punctuation]

    stop_words = set(stopwords.words('english'))\

    negative_words = {'hated','worst','boring','Terrible','Not','no sense','disappointing','Waste','never','dull'}

    stop_words = stop_words - negative_words


    tokens = [word for word in tokens if word not in stop_words]
    clean_text = " ".join(tokens)

    return clean_text

print("Cleaning text...")

df['clean_review'] = df['review'].apply(preprocess_text)

print(df[['review', 'clean_review']].head())

print("Converting text into vectors...")

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df['clean_review'])

y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)

print("Training model...")

model = LogisticRegression()

model.fit(X_train, y_train)

print("Predicting sentiments...")

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("\nAccuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))

while True:

    user_review = input("\nEnter movie review (or type quit): ")

    if user_review.lower() == "quit":
        break

    clean_input = preprocess_text(user_review)
    vector_input = vectorizer.transform([clean_input])

    result = model.predict(vector_input)

    if result[0] == 1:
        print("Positive Sentiment")
    else:
        print("Negative Sentiment")

print("Program ended.")